name: Flutter CI/CD

on:
  push:
    branches:
      - main
      - publish_to_firebase

  pull_request:
    branches:
      - main
      - publish_to_firebase

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout My Code
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Use the Eclipse Temurin distribution
          java-version: '17'

      - name: Install Flutter Version 3.24.5
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.4' # Use the required Flutter version

      - name: Install Dependencies
        run: flutter pub get


      - name: Build APK
        run: flutter build apk --release
      - run: ls build/app/outputs/flutter-apk


      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: 1:1028080954876:android:244c7bcb7121026ac05679
          serviceCredentialsFileContent: {{
            "type": "service_account",
            "project_id": "fir-ai-logic",
            "private_key_id": "804877a0045a9ae17c011cd42dc9faf7d283cc7c",
            "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQC/X/0LUeWtycDN\nbnFqJOFp6XkFEEuOZGZ3QGxmRlyf3txSCx2sKhZWjT4OOe5kPsPTzdgdL35r2ZxA\nEnGWEp+xrCrAEN0kilBJcUs3rWuouVYZTTeZ1grZ5wORXWidT8x1Vt/C4q48XsyR\n2N5OZY/2MSOv8HxtZIAxIX2rmgCAxuGjRlTyNjNOUoo3sliS8a7ILXY9coMPZBoN\nuf6xwu75Po2OFoPiktiyPFGGz9cukGlCbE5fy8t1kAPQuzNCmMIEQGS+m1crehEr\nl4vsMeEOHYa7U2LFNuNvLVI7NaFr8DGyiB1Def4sOUt7/1M2yccb2FvncQDf8VAR\nU0G73zpBAgMBAAECggEAHMXEgHdxcfnHmktM03HUjy0qRAvhZDjtm+fMdGsHQYUK\n+G3R6gDQ53XoWtC0ag9yt003PRoXJoVq48oyGCdYKakSK1rNuNDvxb76GVaiPVWS\nH483uRIQgxbjty8FS8OD4K9tSHp2yj5RgOsLb1t/M7tLG4hrWLIXwOtBXvOyOCoM\nAcf+d2Tzo31kXeg+qPO1bYwBU3fOecY6EY3UYRYWmg6zHZcPzxgFaPLHaMkNb8vI\nrjWArG2OpqwJ8fJaA/yF4K596g8BLyvw8NTyBHKKf0X6gIOgHjMZVAfqa/UnJ80r\nt4St79PvTJb3L6e/cOeAWk8XSwXaKSm2dAYWZbJcHQKBgQDnr3ETvZ2M4odbSgom\nm6+O2pmAsPd5HGRnOpVQYTP7fEN/WKiL2IBufnmvSJsho+eNqe0S+yE8JPpcxRqH\ndw1aVyF80rL7hpTB6bCw2WYpx4jXvOw1rmXlhx/Ec8YGHCE9xpR1tzqYDlsGZPq3\nsks7ipc4B/R0Wg1XdPNJ56VGHQKBgQDTdY0PLnDb4Qo2C8KJ16fOOSjDhBkkk/KT\nWQBfspEuPbcGiWV9F4c1A0fjkJLzUOkViLwOphZs74N7aQXI4PwOjHWLZPaH7LRo\n8HdoEEfSy3FzygPVUoqsOx8p8wSCSVZLmNp11sc9Gsatn1ftS9FSQ54L6Kd1boe3\nESI4GWu7dQKBgQDXNEyZpJiSw9ws/MIfCJ/y1rSdKERHGAtfI7iMGC4b3FoqEOVG\nOQ1bFVncalnGzqOIIB4ZcnF1l3eC8obo67nYf3SYqHIeVu0YjgRU0SsnhbNjiZXz\naxI1OOVWKp/3DuwFoM5H5bGkijkc4HFObmuZW+uI3ULBTOB1qylNLcGENQKBgQDD\nQwgnnaW/lHWeZIuWR5p/to5qxH+HJEraP1Q2Cik/vuNUWOlrcp96l3X5sBXSMsOZ\nC/NDv6BzpVQPUHJ0BTUbph4gwvFXoH8TbAGHCYmZIB26Yy/Y+2hsFAf575sZR+k0\n04ffSp4eUaxmxP4ndFxtD11Q99wydwdBR8QGc4rkxQKBgQDTRfBAgAp2jl147rw8\nMsUb3RG7zXir92gxfh3DHePoNuo6fO7tAEzPADxMN9XJbuisga6n1z/6khhh+ssC\n7JBulkXVADmy2jzYNQGwTfCa0FyP6+1s+o0Ji+aDDg5pEoNaxPYS0KBW1CfU2Aex\njUbsDrgNOW9I4GtpltQSDkwG6w==\n-----END PRIVATE KEY-----\n",
            "client_email": "app-distribution-service@fir-ai-logic.iam.gserviceaccount.com",
            "client_id": "107057434309417162513",
            "auth_uri": "https://accounts.google.com/o/oauth2/auth",
            "token_uri": "https://oauth2.googleapis.com/token",
            "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
            "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/app-distribution-service%40fir-ai-logic.iam.gserviceaccount.com",
            "universe_domain": "googleapis.com"
          }}

          groups: testers
          file: build/app/outputs/flutter-apk/app-release.apk
      